title: Joe píše
description: Joe upřímně neupřímně píše o svém studium i životě.

url: blog.josefkolar.cz
baseurl: ""
paginate_path: "blog/page:num/"
permalink: pretty

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 # - title:
 #  url: /index.html
 #- title: About
 #  url: /about
 #- title: Contact
 #  url: /contact

social:
   github: thejoeejoee
   twitter: thejoeejoee
   facebook: kolar.joe
   email: mail@josefkolar.cz

# google_analytics: "UA-58263416-1"
